### ISSUE TITLE
RuntimeWarning: invalid value encountered

### ISSUE THREAD

**Issue by jfkrizmanic** [NuSpaceSim/nuSpaceSim#23]
Runs with altitude = 3 km report the following:

─────────────────────────────────  NuSpaceSim ──────────────────────────────────
[15:54:23] Running NuSpaceSim with Energy Spectrum                              
           (MonoSpectrum(log_nu_tau_energy=12.0))                               
           Computing  Geometries.                                               
[15:54:24]         Threw 1000000 neutrinos. 833000 were valid.                  
           Computing  Energy Spectra.                                           
           Computing  Taus.                                                     
[15:54:25] Computing  Decay Altitudes.                                          
           Computing  EAS Optical Cherenkov light.                              
[########################################] | 100% Completed | 18min 16.8s
[16:12:49] Computing  Optical Monte Carlo Integral.                             
                   Monte Carlo Integral [Optical]: 0.28800625990585454          
                   Monte Carlo Integral, GEO Only [Optical]: 23.265809835098278 
                   Number of Passing Events [Optical]: 605498                   

           Computing  EAS Radio signal.               
** ... nuspacesim/simulation/eas_radio/radio.py:36: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(r2squared * cosexit * cosexit - r2squared + r1 * r1) - r2 * cosexit
**
 
[16:13:57] Computing  Radio Monte Carlo Integral.                               
                   Monte Carlo Integral [Radio]: 0.03246948435935298            
                   Monte Carlo Integral, GEO Only [Radio]: 28.506907465350796   
                   Number of Passing Events [Radio]: 32465                      
                                                                                
            ✨ Done ✨

**Comment by aludez** [comment]
I fixed this by switching the distance calculation I was doing for scaling to instead use distance_to_detector from eas_optical/detector_geometry.py
