### ISSUE TITLE
Facilitating use by established experiments

### ISSUE THREAD

**Issue by emayotte** [NuSpaceSim/nuSpaceSim#28]
If EAS data can be output in a .long file like format or Conex like output, currently established experiments can use the simulations as read-in to their own detector simulation software.

If possible Conex like would be easiest to implement, but wouldn't allow for later use of Cherenkov light by experiments as Conex doesn't generate.
 
For the case of CORSIKA like, an example CORSIKA long file is included below (as a .txt instead of .long).

Generally the format is a table split in variable steps (defined in file header) with the following columns of particle counts (excluding depth which is simply the current slant depth step)

DEPTH   GAMMAS   POSITRONS   ELECTRONS   MU+  MU-   HADRONS   CHARGED   NUCLEI   CHERENKOV

Halfway through the table is repeated with the steps out of phase with new columns of

DEPTH   GAMMA    EM IONIZ    EM CUT    MU IONIZ    MU CUT    HADR IONIZ    HADR CUT   NEUTRINO    SUM  

These second column steps are not used by experiments I have participated in and wouldn't be needed for this purpose. 

At the end is a fit to a GH profile with the resulting parameters and ChiSq values reported.

[Corsika-long.txt](https://github.com/NuSpaceSim/nuSpaceSim/files/8004468/Corsika-long.txt)

**Comment by Areustle** [comment]
Better addressed by #33 . Closing.
