### ISSUE TITLE
Need compute.py to distinguish between diffuse and too calculations

### ISSUE THREAD

**Issue by tventers** [NuSpaceSim/nuSpaceSim#50]
Currently, I have to install nuspacesim in distinct environments for diffuse and ToO calculations. We need to change compute.py so that it can run both types of calculations and selects the one that is appropriate for the calculation selected by the user.

**Comment by Areustle** [comment]
Related to Issue #36

**Comment by Areustle** [comment]
Fixed in the main branch. merged.
