### ISSUE TITLE
Hardcoded 525km and 1e17 eV in cphotang

### ISSUE THREAD

**Issue by aludez** [NuSpaceSim/nuSpaceSim#6]
Detector height is hard coded to 525km and shower energy is hard coded to 1e17 eV in [EASchergen/photang.py](https://github.com/NuSpaceSim/nuSpaceSim/blob/main/nuSpaceSim/EAScherGen/cphotang.py#L70-L75)

I (sort of) fixed this in my radioBranch commit by passing in the config file and reading from that. 
However, I think logE is supposed to be the shower energy, so you probably have to pass in that whole array.

**Comment by Areustle** [comment]
Addressed with the inclusion of 1/r^2 scaling in cphotang.py, commit d85396957d76fa1f47236af7fea301240cc12eb4.
Waiting for @jfkrizmanic to validate.

**Comment by Areustle** [comment]
Addressed!
