### ISSUE TITLE
Shower energy is a constant on cphotang.py

### ISSUE THREAD

**Issue by Jorgecvb1** [NuSpaceSim/nuSpaceSim#68]
The src/nuspacesim/simulation/eas_optical/cphotang.py script, which calculates the profiles and cherenkov photons of every shower, currently has a fixed shower energy parameter = 10^17 eV (self.Eshow which is defined with self.logE=17.0)

This is the relevant line in the code
https://github.com/NuSpaceSim/nuSpaceSim/blob/92decf4be9eae11cd3c1aadc53b9a905383e1765/src/nuspacesim/simulation/eas_optical/cphotang.py#L190

This should be changed to be the shower's energy (Tau energy * FracETauInShower )

**Comment by Areustle** [comment]
@jfkrizmanic Is the correct procedure here to still scale by the showerEnergy again afterwards in computing the numPEs?

https://github.com/NuSpaceSim/nuSpaceSim/blob/92decf4be9eae11cd3c1aadc53b9a905383e1765/src/nuspacesim/simulation/eas_optical/eas.py#L96-L101

**Comment by Areustle** [comment]
I've opened a pull request (#69 ) with the changes I think are needed to fix this bug.

ShowerEnergy from the taus package is in units of 100PeV (10^17eV). So I scaled it by 10^11 to convert to MeV for the Greisen parameterization. Should the units be in a different order of magnitude?

**Comment by Areustle** [comment]
See the full set of diffs here 
https://github.com/NuSpaceSim/nuSpaceSim/pull/69/files

**Comment by Jorgecvb1** [comment]
I think they should be in GeV, since Ecrit is defined in those units, but @jfkrizmanic should confirm
