### ISSUE TITLE
Data selection for plots: only events with Npe >=photo_electron_threshold should be displayed

### ISSUE THREAD

**Issue by jfkrizmanic** [NuSpaceSim/nuSpaceSim#94]
Since all data are currently placed in the plot, 'interesting' features appear, such as default values when Npe=0, only events with Npe >=photo_electron_threshold should be displayed as a default, we could add a variable to adjust the Npe threshold for plotting to expand the capablitity

**Comment by Areustle** [comment]
Merged into ToO, then merged into main
